Add useful troubleshooting information to the log collector
awslabs/ecs-logs-collector pull request #22
Opened 2017-09-14 10:26 UTC by overdrive3000

Add vmststat and network information to the ecs-log-collector script

The vmststat output will allow troubleshooting if the Instance running the ECS tasks is facing I/O issues, useful to quickly check if the issue is because the EBS volume is running out IOPS

Network status will allow us to check if there is something wrong with the network interfaces or even if there was a change in the OS route table which is affecting docker.

2017-09-18 23:16 UTC, jhaynes requested changes
This looks good to me. One nitpicky comment.

2017-09-18 23:16 UTC, jhaynes commented on ecs-logs-collector.sh
> +  /sbin/ip link > ${info_system}/ip_link.txt
Why do you have absolute paths for `ip` and `netstat`? Since these are fairly standard tools, I think we can expect them to be on the users path like we do with other commands, e.g. `vmstat`.

2017-12-21 00:13 UTC, jahkeup requested changes

2017-12-21 00:13 UTC, jahkeup commented on ecs-logs-collector.sh
> +  vmstat 1 5 > ${info_system}/vmstat.txt
This is a great additional data point to gather, thanks! I think this ought to be broken out into its own function complete with a note saying its going to look idle for a moment.

2020-11-29 18:49 UTC, hugoprudente commented
Is this gonna get merged?

2021-11-15 23:03 UTC, closed without merging