Support for ECS 2 AMI
awslabs/ecs-logs-collector pull request #47
Opened 2018-11-01 23:44 UTC by fjromerom

### Summary

- Provides support for the new ECS 2 AMI
- Removed broken and unnecessary echo within the try_set_instance_infodir() function.
- Using mode debug, it created an additional directory to write the output of "last" because it loaded twice the init() function. I removed it from the get_sysinfo() function, because first I don't know why this is included in this function since it's not system info per se and second I don't see any reason why we may need this information, I've never used it.

### Testing

- [X] Works properly on Amazon Linux
- [X] Works properly on Amazon Linux 2
- [X] Works properly on RHEL 7
- [X] Works properly on Debian 8
- [X] Works properly on Ubuntu 14.04

New tests cover the changes: yes

### Licensing

This contribution is under the terms of the Apache 2.0 License:

2018-11-02 20:02 UTC, jahkeup requested changes
@fjromerom thanks for tackling the addition of AL2 to the log collector!

I like the overall approach, and have a few pieces of feedback and changes I think we should make before merging this.

2018-11-02 20:02 UTC, jahkeup commented on ecs-logs-collector.sh
> +      chkconfig --list > ${info_system}/services.txt 2>&1
AL2 is systemd based, so we should gather the services with `systemctl`, like so:

```suggestion
      systemctl list-units > ${info_system}/services.txt 2>&1
```

2018-11-02 20:02 UTC, jahkeup commented on ecs-logs-collector.sh
> +          /sbin/service docker restart
Restart on AL2 should use `systemctl` to interact with the `docker.service`, like:

```suggestion
          systemctl restart docker.service
```

2018-11-02 20:02 UTC, jahkeup commented on ecs-logs-collector.sh
> +
nit: can we drop this extra newline?

2018-11-02 20:02 UTC, jahkeup commented on ecs-logs-collector.sh
> +        systemctl restart ecs
AL AMI will need to keep the upstart instructions to restart the Agent:
```suggestion
        stop ecs; start ecs
```

2018-11-02 20:02 UTC, jahkeup commented on ecs-logs-collector.sh
>        then
The code in the case statements are relatively similar in both the `amazon` and `amazon2` cases, can we combine them until the point they diverge (ie: the primary difference is `systemctl restart ecs.service` vs `stop ecs; start ecs`)?

Something like:

```bash
case "${os_name}" in
  amazon|amazon2)
    if [ -e /etc/ecs/ecs.config ] &&  grep -q "^\s*ECS_LOGLEVEL=debug" /etc/ecs/ecs.config
    then
      info "Debug mode is already enabled."
    else
      echo "ECS_LOGLEVEL=debug" >> /etc/ecs/ecs.config
    fi
    
    try "restart the Amazon ECS Container Agent to enable debug mode"
    case "${os_name}" in
      amazon) stop ecs; start ecs ;;
      amazon2) systemctl restart ecs.service ;;
    esac
    ;;
  *)
    warning "the current operating system is not supported."
    ;;
esac
```

Though we could apply this same pattern to the docker debug case (updated above), I think that we should leave it as there may be further updates and differences that are likely to be handled in the case of AL2 where ecs won't.

2018-11-02 20:02 UTC, jahkeup commented on ecs-logs-collector.sh
> +        /bin/journalctl -u docker > ${dstdir}/docker
Let's quote the use of the `${dstdir}` here for expansion's sake and not call `journalctl` by absolute path, instead lets let it be anywhere on the path with plain ol `journalctl -u docker`.
```suggestion
        journalctl -u docker > "${dstdir}"/docker
```

2018-11-03 22:41 UTC, fjromerom commented on ecs-logs-collector.sh
> +      chkconfig --list > ${info_system}/services.txt 2>&1
Agree.

2018-11-03 22:41 UTC, fjromerom commented on ecs-logs-collector.sh
> +          /sbin/service docker restart
It also works with service but I agree.

2018-11-03 22:43 UTC, fjromerom commented on ecs-logs-collector.sh
> +
I just wanted to keep the same structure in the case. We can agree a structure for next releases.

2018-11-03 22:44 UTC, fjromerom commented on ecs-logs-collector.sh
> +        systemctl restart ecs
Yep, that's right.

2018-11-03 22:52 UTC, fjromerom commented on ecs-logs-collector.sh
>        then
I thought about that as well but I wanted to do as minor changes as possible to support AL2. I will combine them in the next update.

2018-11-03 23:05 UTC, fjromerom commented on ecs-logs-collector.sh
> +        /bin/journalctl -u docker > ${dstdir}/docker
That sounds good for me. I just kept the same format as other Systemd systems, so if we change this we should change the others too. Also, every mention to `${dstdir}` is not quoted, I would leave these changes for the next update so they all are updated in the same commit.

2018-11-06 20:47 UTC, jahkeup approved these changes
This looks good to move forward with! There are a couple more changes that could be made, but aren't necessary to merge.

2018-11-06 20:47 UTC, jahkeup commented on ecs-logs-collector.sh
> +
I'm all for incremental improvements, I don't see a reason to not include such an improvement with this change. Please do if its practical to do so.

2018-11-06 20:47 UTC, jahkeup commented on ecs-logs-collector.sh
> +        /bin/journalctl -u docker > ${dstdir}/docker
I'm all for incremental improvements, and though the precedent exists (much of this appears to be copied from there), I would prefer we take this opportunity to make this addition better than what came before :)

2018-11-06 20:47 UTC, jahkeup commented on ecs-logs-collector.sh
>        then
I don't see a good reason to not make this change given it cleans this up; that said we don't have to change it either. I'll leave it to your discretion.

2018-11-13 16:06 UTC, merged