Cleaning code to remove some errors on console
awslabs/ecs-logs-collector pull request #48
Opened 2018-11-07 15:58 UTC by mfortin

### Summary
Fixes 2 errors on the console:

Trying to check if the script is running as root ... ok
Trying to resolve instance-id ... /usr/local/bin/ecs-logs-collector.sh: line 175: /usr/local/bin/collect/i-0873c22d6476fe6d3/system/instance-id.txt: No such file or directory
ok
Trying to collect system information ... ok
Trying to check disk space usage ... ok
Trying to collect common operating system logs ... ok
Trying to collect kernel logs ... ok
Trying to get mount points and volume information ... ok
Trying to check SELinux status ... ok
Trying to get iptables list ... ok
Trying to detect installed packages ... ok
Trying to detect active system services list ... ok
Trying to gather Docker daemon information ... ok
Trying to inspect all Docker containers ... ok
Trying to collect Docker daemon logs ... ok
Trying to collect Amazon ECS Container Agent logs ... ok
Trying to collect Amazon ECS Container Agent state and config ... ok
Trying to collect Amazon ECS Container Agent engine data ... ok
Trying to collect Amazon ECS init logs ... cp: cannot stat '/var/log/ecs/ecs-init.log*': No such file or directory
ok
Trying to archive gathered log information ... ok

### Implementation details
Creating folder to copy instance id and using a redirect instead of pipe to echo.
ECS init logs are optional and not necessarily present when not running and Amazon AMI.

### Testing
- [X] Works properly on Amazon Linux
- [X] Works properly on RHEL 7
- [X] Works properly on Debian 8
- [X] Works properly on Ubuntu 14.04

New tests cover the changes: no

### Licensing
This contribution is under the terms of the Apache 2.0 License: yes

2018-11-13 16:34 UTC, jahkeup approved these changes
Glad these changes were proposed! I had similar changes staged in my repo too :+1:

I have a couple minor edits that we'll need before we can merge this. Can you also rebase on `master`?

Thanks!

2018-11-13 16:34 UTC, jahkeup commented on ecs-logs-collector.sh
> +  for entry in $(ls /var/log/ecs/ecs-init.log* 1> /dev/null 2>&1); do
This prevents the output from making its way to the loop, I think instead we'd want to make only the warning go to `/dev/null`:

```suggestion
  for entry in $(ls /var/log/ecs/ecs-init.log* 2>/dev/null); do
```

2018-11-13 16:34 UTC, jahkeup commented on ecs-logs-collector.sh
> +      mkdir -p ${info_system}
Quick fix: please quote the path here (ie: `mkdir -p "${info_system}"`).

2018-11-13 16:34 UTC, jahkeup requested changes
Sorry, clicked the wrong button. Please see earlier review comments!

2018-11-13 16:43 UTC, jahkeup commented on ecs-logs-collector.sh
> +      mkdir -p ${info_system}
This change may make it in with #45, so let's keep an eye on this when rebasing.

2018-11-13 17:38 UTC, mfortin commented
Rebased with master. Applied your suggestion.

2019-01-14 17:14 UTC, yunhee-l commented
Closing this in favor of https://github.com/awslabs/ecs-logs-collector/pull/49.

2019-01-14 17:14 UTC, closed without merging

2019-01-15 14:11 UTC, mfortin commented
There are still some errors.

`Trying to check if the script is running as root ... ok
Trying to resolve instance-id ... ok
Trying to collect system information ... ok
Trying to check disk space usage ... ok
Trying to collect common operating system logs ... ok
Trying to collect kernel logs ... ok
Trying to get mount points and volume information ... ok
Trying to check SELinux status ... ok
Trying to get iptables list ... ok
Trying to detect installed packages ... ok
Trying to detect active system services list ... ok
Trying to gather Docker daemon information ... ok
Trying to inspect all Docker containers ... ok
Trying to collect Docker daemon logs ... ok
Trying to collect Amazon ECS Container Agent logs ... ok
Trying to collect Amazon ECS Container Agent state and config ... ok
Trying to collect Amazon ECS Container Agent engine data ... ok
Trying to collect Amazon ECS init logs ... cp: cannot stat '/var/log/ecs/ecs-init.log*': No such file or directory
ok
Trying to archive gathered log information ... ok`

ECS Init is optional when not using Amazon Linux AMI.